#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

#
# Run test to check correct output of #`status scheduler job=...`
# of a copy job whose client is disabled
#

start_test

cat <<END_OF_DATA >$tmp/bconcmds
messages
@$out $tmp/log3.out w
status scheduler job=copy

@$out $tmp/log4.out w
disable client=bareos-fd
status scheduler job=copy
wait
messages
quit
END_OF_DATA

run_bconsole

#check that `status scheduler job=...` returns scheduled copy jobs
if ! grep "TestCycle               Level=Full" "$tmp"/log3.out; then
  echo "'TestCycle               Level=Full' not found in $tmp/log3.out" >&2
  estat=1
fi

#check that `status scheduler job=...` returns nothing when we disable the client
if ! grep "TestCycle
                            copy (disabled)

           ====
            " "$tmp"/log2.out ||
    grep "TestCycle               Level=Full" "$tmp"/log4.out; then
  echo "a scheduled job was listed in $tmp/log4.out" >&2
  estat=1
fi

end_test
